apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
  labels:
    jenkins-agent: static
    jenkins/jenkins-jenkins-agent: "true"
spec:
  containers:
    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true

    - name: python-test
      image: glengold/images:python_pytest_requests
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: false

  volumes:
    - name: docker-socket
      hostPath:
        path: /var/run/docker.sock
        type: Socket
