apiVersion: v1
kind: Pod
metadata:
  name: jenkins-agent-pod
spec:
  containers:
    - name: docker-dind
      image: docker:19.03.12-dind
      securityContext:
        privileged: true
      env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
      ports:
        - containerPort: 2375

    - name: ez-docker-helm-build
      image: ezezeasy/ez-docker-helm-build:1.41
      imagePullPolicy: Always
      securityContext:
        privileged: true
      env:
        - name: DOCKER_HOST
          value: "tcp://localhost:2375"
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker

    - name: python-test
      image: python:3.9-slim
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: false

    - name: docker-compose
      image: docker/compose:latest
      command: ["sleep"]
      args: ["infinity"]
      imagePullPolicy: Always
      securityContext:
        privileged: true

  volumes:
    - name: dind-storage
      emptyDir: {}
